version: '3'
services:
  go:
    image: golang:1.17.2-stretch
    working_dir: /usr/src/myapp
    volumes:
      - $PWD:/usr/src/myapp

  python:
    image: python:3.8.12-bullseye
    working_dir: /usr/src/myapp/example/python
    volumes:
      - $PWD:/usr/src/myapp

  js:
    build:
      context: .
      dockerfile: example/js/Dockerfile
    working_dir: /usr/src/myapp/example/js
    volumes:
      - $PWD/:/usr/src/myapp/
      - /usr/src/myapp/example/js/node_modules

  ruby:
    build:
      context: .
      dockerfile: example/ruby/Dockerfile
    working_dir: /usr/src/myapp/example/ruby
    volumes:
      - $PWD/:/usr/src/myapp/
      - /usr/src/myapp/example/ruby/vendor

  php:
    build:
      context: .
      dockerfile: example/php/Dockerfile
    working_dir: /usr/src/myapp/example/php
    volumes:
      - $PWD:/usr/src/myapp