services:
  go:
    image: golang:1.17.2-stretch
    working_dir: /usr/src/myapp
    volumes:
      - .:/usr/src/myapp

  python:
    image: python:3.10-bullseye
    working_dir: /usr/src/myapp/example/python
    volumes:
      - .:/usr/src/myapp
    environment:
      LD_LIBRARY_PATH: "."

  js:
    build:
      context: .
      dockerfile: example/js/Dockerfile
    working_dir: /usr/src/myapp/example/js
    volumes:
      - ./:/usr/src/myapp/
      - /usr/src/myapp/example/js/node_modules

  ruby:
    build:
      context: .
      dockerfile: example/ruby/Dockerfile
    working_dir: /usr/src/myapp/example/ruby
    volumes:
      - ./:/usr/src/myapp/
      - /usr/src/myapp/example/ruby/vendor

  php:
    build:
      context: .
      dockerfile: example/php/Dockerfile
    working_dir: /usr/src/myapp/example/php
    volumes:
      - .:/usr/src/myapp
    environment:
      LD_LIBRARY_PATH: "."